# Author:  Niels A.D.
# Project: gowarcraft3 (https://github.com/nielsAD/gowarcraft3)
# License: Mozilla Public License, v2.0

language: go
go: 1.10.x

os:
  - linux
  - osx

notifications:
  email:
    on_success: false
    on_failure: change

install:
  # Install OS dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpcap-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install libpcap; fi

  # Install golang dependencies
  - go get github.com/google/gopacket
  - go get github.com/golang/lint/golint

  # Compile vendor dependencies
  - cd ./vendor/StormLib; cmake .; make; cd ../..


script:
  - gofmt -l .
  - go build ./...
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status ./...
