# Author:  Niels A.D.
# Project: gowarcraft3 (https://github.com/nielsAD/gowarcraft3)
# License: Mozilla Public License, v2.0

language: go
go: 1.10.x

os:
  - linux
  - osx

notifications:
  email:
    on_success: false
    on_failure: change

install:
  # Install OS dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpcap-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install libpcap; fi

  # Install test dependencies
  - go get github.com/golang/lint/golint

script:
  - make test
  - make release
